### ISSUE TITLE
What LightBlue really is?

### ISSUE THREAD

**Issue by alexsandro-xpt** [LightBlueProject/LightBlue#94]
I'm looking for an alternative for Azure Storage Emulation on my local network to keep same scenery of online Azure infracture.

I need upload 200GB of images to Azure Storage Emulation, but I dont't know if it's suport.

LightBlue Storage could help me for that?

**Comment by ColinScott** [comment]
Probably not. It's a thin wrapper over the local file system that stores everything in AppData. It's also nowhere near 100% compatible. It's intended for some relatively narrow development usecases rather than being a full replacement implementation.
